AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  python3.11

Globals:
  Function:
    Timeout: 180

Resources:
  # TODO: generate usage plan linked to this apikey
  # TODO: generate eventBridge scheduling schema for scheduling message

  WoofAuomationApiKey:
    Type: AWS::ApiGateway::ApiKey
    Properties:
      Name: LambdasApiKey
      Description: API key for those LambdasApiKey

  WoofAutomationApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      Auth:
        ApiKeyRequired: true

  SendBotMessageFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Architectures:
        - x86_64
      Events:
        SendBotMessage:
          Type: Api
          Properties:
            Path: /send-bot-message
            Method: post
            RestApiId:
              Ref: WoofAutomationApi
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./lambdas/send_bot_message
      DockerTag: python3.11-v1

  SaveIdeaToDBFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Architectures:
        - x86_64
      Events:
        SaveIdeaToDB:
          Type: Api
          Properties:
            Path: /save-to-db
            Method: post
            RestApiId:
              Ref: WoofAutomationApi
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./lambdas/save_to_db
      DockerTag: python3.11-v1

  ProcessPostIdeasFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Architectures:
        - x86_64
      Events:
        ProcessPostIdeas:
          Type: Api
          Properties:
            Path: /process-post-ideas
            Method: post
            RestApiId:
              Ref: WoofAutomationApi
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./lambdas/process_post_ideas
      DockerTag: python3.11-v1

  ProcessPromptsFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Architectures:
        - x86_64
      Events:
        PromptsIdeas:
          Type: Api
          Properties:
            Path: /process-prompts
            Method: post
            RestApiId:
              Ref: WoofAutomationApi
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./lambdas/process_prompts
      DockerTag: python3.11-v1

Outputs:
  WoofAutomationApi:
    Description: API Gateway URL
    Value:
      Fn::Sub:
        - https://${Api}.execute-api.${AWS::Region}.amazonaws.com/${Stage}/
        - Api: !Ref WoofAutomationApi
          Stage: prod

  SendBotMessageFunction:
    Description: ARN of the SendBotMessageFunction
    Value:
      Fn::GetAtt:
        - SendBotMessageFunction
        - Arn

  SaveIdeaToDBFunction:
    Description: ARN of the SaveIdeaToDBFunction
    Value:
      Fn::GetAtt:
        - SaveIdeaToDBFunction
        - Arn
        
  ProcessPostIdeasFunction:
    Description: ARN of the ProcessPostIdeasFunction
    Value:
      Fn::GetAtt:
        - ProcessPostIdeasFunction
        - Arn

  ProcessPromptsFunction:
    Description: ARN of the ProcessPromptsFunction
    Value:
      Fn::GetAtt:
        - ProcessPromptsFunction
        - Arn        
