AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  python3.11

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 180

Resources:
  WoofAuomationApiKey:
    Type: AWS::ApiGateway::ApiKey
    Properties:
      Name: LambdasApiKey
      Description: API key for those LambdasApiKey

  WoofAutomationApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      Auth:
        ApiKeyRequired: true

  GenerateImageFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      PackageType: Image
      Architectures:
        - x86_64
      Events:
        GenerateImage:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /generate-image
            Method: post
            RestApiId:
              Ref: WoofAutomationApi

    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./generate_image
      DockerTag: python3.11-v1

  SendBotMessageFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      PackageType: Image
      Architectures:
        - x86_64
      Events:
        SendBotMessage:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /send_bot_message
            Method: post
            RestApiId:
              Ref: WoofAutomationApi

    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./send_bot_message
      DockerTag: python3.11-v1

Outputs:
  WoofAutomationApi:
    Description: API Gateway URL
    Value:
      Fn::Sub:
        - https://${Api}.execute-api.${AWS::Region}.amazonaws.com/${Stage}/
        - Api: !Ref WoofAutomationApi
          Stage: prod

  GenerateImageFunction:
    Description: ARN of the GenerateImageFunction
    Value:
      Fn::GetAtt:
        - GenerateImageFunction
        - Arn

  SendBotMessageFunction:
    Description: ARN of the SendBotMessageFunction
    Value:
      Fn::GetAtt:
        - SendBotMessageFunction
        - Arn
